/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author garoui
 */
public class ConsulterRDVS extends javax.swing.JFrame {

    /**
     * Creates new form ConsulterRDVS
     */
     Connexion conn=new Connexion();
   Statement stm;
   ResultSet Rs;
   DefaultTableModel model=new DefaultTableModel();

    public ConsulterRDVS() {
        initComponents();
   model.addColumn("IDR");
model.addColumn("IDP");
model.addColumn("dateRDV");
model.addColumn("nomP");
model.addColumn("prenomP");
model.addColumn("tarif");
model.addColumn("commentaire");
try {
stm=(Statement) conn.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select * from rendezvous");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("IDR"),Rs.getString("IDP"),Rs.getString("dateRDV"),
    Rs.getString("nomP"),Rs.getString("prenomP"),Rs.getString("tarif"),Rs.getString("commentaire")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("consultation des rendez-vous");
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Les Rendez-Vous Des Patients");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 10, 450, 70);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id patient", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 210, 790, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication4/les images/RPWP7T7RKLX5MN6XVOOZ4AZJ7Y.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1700, 1167));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -160, 1280, 800);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 870, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        // TODO add your handling code here: 
        try {  int i=tble.getSelectedRow();
            
            //sa si quant on hoisir un nom dans le tableau il va afficher sur les fieldtext
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"erreur selectionne\n"+e.getMessage());
        }
    }//GEN-LAST:event_tbleMouseClicked

    /**
     * @param args the command line arguments
     */

    private void afficher(){
    try {
 model.setRowCount(0);
stm=(Statement) conn.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select * from rendezvous");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("IDR"),Rs.getString("IDP"),Rs.getString("dateRDV"),
    Rs.getString("nomP"),Rs.getString("prenomP"),Rs.getString("tarif"),Rs.getString("commentaire")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsulterRDVS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsulterRDVS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsulterRDVS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsulterRDVS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsulterRDVS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tble;
    // End of variables declaration//GEN-END:variables
}
