/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author garoui
 */
public class gererConsultations extends javax.swing.JFrame {

    /**
     * Creates new form gererConsultations
     */
     Connexion conn=new Connexion();
   Statement stm;
   ResultSet Rs;
   DefaultTableModel model=new DefaultTableModel();
    public gererConsultations() {
        initComponents();
        model.addColumn("IDC");
model.addColumn("IDP");
model.addColumn("nomP");
model.addColumn("prenomP");
model.addColumn("dateCslt");
model.addColumn("commentaire");
try {
stm=(Statement) conn.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select * from consultation");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("IDC"),Rs.getString("IDP"),
    Rs.getString("nomP"),Rs.getString("prenomP"),Rs.getString("dateCslt"),Rs.getString("commentaire")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        dd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DES CONSULTATIONS");
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION DES CONSULTATIONS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 30, 500, 50);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("id patient");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 100, 80, 18);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("nom patient");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(237, 100, 90, 18);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("prenom patient");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 100, 120, 18);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("date consultation");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(489, 100, 131, 18);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("commentaire");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(640, 100, 110, 18);

        jLabel7.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("id consultation");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 100, 120, 20);

        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c);
        c.setBounds(640, 120, 120, 30);
        jPanel1.add(d);
        d.setBounds(490, 120, 130, 30);

        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        jPanel1.add(p);
        p.setBounds(360, 120, 110, 30);

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        jPanel1.add(n);
        n.setBounds(240, 120, 100, 30);
        jPanel1.add(id);
        id.setBounds(130, 120, 40, 30);
        jPanel1.add(dd);
        dd.setBounds(10, 120, 40, 30);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 760, 60);

        jButton3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton3.setText("MODIFIER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(300, 200, 160, 40);

        jButton4.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton4.setText("SUPPRIMER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(520, 200, 160, 40);

        jButton5.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton5.setText("AJOUTER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(110, 200, 130, 40);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication4/les images/RPWP7T7RKLX5MN6XVOOZ4AZJ7Y.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, -20, 830, 530);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 510);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String IDC=dd.getText();
String IDP=id.getText();
String nomP=n.getText();
String prenomP=p.getText();
String dateCslt=d.getText();
String commentaire=c.getText();
String req="INSERT INTO consultation(IDC,IDP,nomP,prenomP,dateCslt,commentaire)VALUES('"+IDC+
        "','"+IDP+"','"+nomP+"','"+prenomP+"','"+dateCslt+"','"+commentaire+"')";
try {
    stm=(Statement) conn.obtenirconnexion().createStatement();
//stm.executeQuery(req);
stm.executeUpdate(req);
JOptionPane.showMessageDialog(null,"le CONSULTATION est ajoutée correctement !");//
id.setText("");
n.setText("");
p.setText("");
d.setText("");
c.setText("");
afficher();
}
catch(SQLException e){System.err.println(e);
JOptionPane.showMessageDialog(null,"veuillez changer le num id parce que est déja attribue pour une autre consultation!!! ");
    }   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        // TODO add your handling code here:
         try {  int i=tble.getSelectedRow();
            deplace(i);
            //sa si quant on hoisir un nom dans le tableau il va afficher sur les fieldtext
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"erreur selectionne\n"+e.getMessage());
        }
    }//GEN-LAST:event_tbleMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   try {
             if(JOptionPane.showConfirmDialog(null,"attention vous avez supprimer une consultation,est ce que tu es sure?"
                     ,"RDV supprimé",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
         
            if(d.getText().length() != 0){
        stm.executeUpdate("Delete From consultation where IDC = "+dd.getText());
        afficher();
             }//ca est pour recharger la list des stagiaire
            
            else { JOptionPane.showMessageDialog(null,"veuillez remplir le champ id !");}
        
        }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de supprission \n"+e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try { 
            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {

                stm.executeUpdate("UPDATE consultation SET nomP='"+n.getText()+"',prenomP='"+p.getText()+"',dateCslt='"+d.getText()+"',commentaire='"+c.getText()+"' WHERE IDC="+dd.getText());  
                afficher();
            } 
        } catch (HeadlessException | SQLException e){JOptionPane.showMessageDialog(null,"erreur de modification !!!!!!!"+e.getMessage());
        System.err.println(e);}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
      private void deplace(int i){
        try{
               dd.setText(model.getValueAt (i, 0).toString());
        id.setText(model.getValueAt (i, 1).toString());
          n.setText(model.getValueAt (i, 2).toString());
          p.setText(model.getValueAt (i, 3).toString());
     d.setText(model.getValueAt (i, 4).toString());
      c.setText(model.getValueAt (i, 5).toString());
        }
        catch(Exception e)
        {
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());
        }
        
    }
    private void afficher(){
    try {
 model.setRowCount(0);
stm=(Statement) conn.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select * from consultation");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("IDC"),Rs.getString("IDP"),
    Rs.getString("nomP"),Rs.getString("prenomP"),Rs.getString("dateCslt"),Rs.getString("commentaire")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gererConsultations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gererConsultations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gererConsultations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gererConsultations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gererConsultations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField dd;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n;
    private javax.swing.JTextField p;
    private javax.swing.JTable tble;
    // End of variables declaration//GEN-END:variables
}
