/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

/**
 *
 * @author garoui
 */
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class GestionRDV extends javax.swing.JFrame {

    /**
     * Creates new form GestionRDV
     */
    Connexion conn=new Connexion();
   Statement stm;
   ResultSet Rs;
   DefaultTableModel model=new DefaultTableModel();
    public GestionRDV() {
        initComponents();
model.addColumn("IDR");
model.addColumn("IDP");
model.addColumn("dateRDV");
model.addColumn("nomP");
model.addColumn("prenomP");
model.addColumn("tarif");
model.addColumn("commentaire");
try {
stm=(Statement) conn.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select * from rendezvous");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("IDR"),Rs.getString("IDP"),Rs.getString("dateRDV"),
    Rs.getString("nomP"),Rs.getString("prenomP"),Rs.getString("tarif"),Rs.getString("commentaire")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        re = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        r = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        j = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gestion des rendez-vous");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(712, 350));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                    LES RENDEZ-VOUS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 10, 320, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATE RENDEZ-VOUS :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 110, 140, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IDR :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 50, 90, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("nom patient :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 140, 110, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("prenom patient :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 170, 100, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("tarif :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 200, 100, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("commentaire :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 230, 110, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IDPatient :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 80, 90, 20);
        jPanel1.add(c);
        c.setBounds(170, 220, 110, 30);
        jPanel1.add(t);
        t.setBounds(170, 190, 110, 30);
        jPanel1.add(p);
        p.setBounds(170, 160, 110, 30);
        jPanel1.add(n);
        n.setBounds(170, 130, 110, 30);
        jPanel1.add(re);
        re.setBounds(170, 100, 110, 30);
        jPanel1.add(d);
        d.setBounds(170, 70, 110, 30);
        jPanel1.add(r);
        r.setBounds(170, 40, 110, 30);

        tble.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 680, 100);

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton1.setText("AJOUTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(500, 90, 150, 30);

        jButton2.setText("ACTUALISER");
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 380, 230, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton3.setText("SUPPRIMER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(500, 170, 150, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton4.setText("RECHERCHE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(500, 40, 150, 40);
        jPanel1.add(j);
        j.setBounds(660, 50, 30, 30);

        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton5.setText("MODIFIER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(500, 130, 150, 30);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication4/les images/depositphotos_193586504-stock-photo-medical-technology-network-team-meeting.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 840, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, 1, 860, 430);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        // TODO add your handling code here:
        try {  int i=tble.getSelectedRow();
            deplace(i);
            //sa si quant on hoisir un nom dans le tableau il va afficher sur les fieldtext
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"erreur selectionne\n"+e.getMessage());
        }
    }//GEN-LAST:event_tbleMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            try {
           model.setRowCount(0);// pour vider la list des client
      {
       Rs = stm.executeQuery("Select * From rendezvous WHERE IDR = '"+r.getText()+"'");
       }while (Rs.next()){
       
       Object [] rendezvous ={Rs.getInt(1),Rs.getInt(2),Rs.getString(3),Rs.getString(4),Rs.getString(5),Rs.getString(6),Rs.getString(7)};
     model.addRow(rendezvous);
       } if (model.getRowCount () == 0){JOptionPane.showMessageDialog(null,"il y a aucune rendez-vous!!!!");
       
       } else{ int i=0;
       deplace(i);
       }
       
       }catch (Exception e) { System.err.println(e);
       JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String IDR=r.getText();
String IDP=d.getText();
String dateRDV=re.getText();
String nomP=n.getText();
String prenomP=p.getText();
String tarif=t.getText();
String commentaire=c.getText();
String req="INSERT INTO rendezvous(IDR,IDP,dateRDV,nomP,prenomP,tarif,commentaire)VALUES('"+IDR+
        "','"+IDP+"','"+dateRDV+"','"+nomP+"','"+prenomP+"','"+tarif+"','"+commentaire+"')";
try {
    stm=(Statement) conn.obtenirconnexion().createStatement();
//stm.executeQuery(req);
stm.executeUpdate(req);
JOptionPane.showMessageDialog(null,"le rendez-vous est ajoutée correctement !");//
d.setText("");
re.setText("");
n.setText("");
p.setText("");
t.setText("");
c.setText("");
afficher();
}
catch(SQLException e){System.err.println(e);
JOptionPane.showMessageDialog(null,"veuillez changer le num id parce que est déja attribue pour un autre rendez-vous!!! ");
    }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          try {
             if(JOptionPane.showConfirmDialog(null,"attention vous avez supprimer un rendez-vous,est ce que tu et sure?"
                     ,"RDV supprimé",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
         
            if(d.getText().length() != 0){
        stm.executeUpdate("Delete From rendezvous where IDR = "+r.getText());
        afficher();
             }//ca est pour recharger la list des stagiaire
            
            else { JOptionPane.showMessageDialog(null,"veuillez remplir le champ id !");}
        
        }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de supprission \n"+e.getMessage());}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            try { 
            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
stm.executeUpdate("UPDATE rendezvous SET nomP='"+n.getText()+"',prenomP='"+p.getText()+"',tarif='"+t.getText()+"',commentaire='"+c.getText()+"' WHERE IDR="+r.getText());
                afficher();
            } 
        } catch (HeadlessException | SQLException e){JOptionPane.showMessageDialog(null,"erreur de modification !!!!!!!"+e.getMessage());
        System.err.println(e);}
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
     private void deplace(int i){
        try{
               r.setText(model.getValueAt (i, 0).toString());
      // txttp.setSelectedItem(dt.getValueAt (i, 5).toString());
        d.setText(model.getValueAt (i, 1).toString());
        // txtb.setSelectedItem(dt.getValueAt (i, 2).toString());
          re.setText(model.getValueAt (i, 2).toString());
          n.setText(model.getValueAt (i, 3).toString());
     p.setText(model.getValueAt (i, 4).toString());
      t.setText(model.getValueAt (i, 5).toString());
      c.setText(model.getValueAt (i, 6).toString());
        }
        catch(Exception e)
        {
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());
        }
        
    }
    private void afficher(){
    try {
 model.setRowCount(0);
stm=(Statement) conn.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select * from rendezvous");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("IDR"),Rs.getString("IDP"),Rs.getString("dateRDV"),
    Rs.getString("nomP"),Rs.getString("prenomP"),Rs.getString("tarif"),Rs.getString("commentaire")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionRDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionRDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionRDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionRDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionRDV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n;
    private javax.swing.JTextField p;
    private javax.swing.JTextField r;
    private javax.swing.JTextField re;
    private javax.swing.JTextField t;
    private javax.swing.JTable tble;
    // End of variables declaration//GEN-END:variables
}
