/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author garoui
 */
public class medecinauth extends javax.swing.JFrame {
    

    /**
     * Creates new form medecinauth
     */
     Connexion conn=new Connexion();
    Statement stm;
    ResultSet Rs;
    
    public medecinauth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l = new javax.swing.JTextField();
        p = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        c = new javax.swing.JButton();
        q = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("page authentification médecin");
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel1.setText("CABINET MEDICALE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(190, 40, 230, 40);

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel2.setText("LOGIN :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 100, 80, 18);

        l.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jPanel2.add(l);
        l.setBounds(180, 100, 140, 30);

        p.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        p.setText("jPasswordField1");
        jPanel2.add(p);
        p.setBounds(180, 150, 140, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel3.setText("PASSWORD :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 150, 110, 30);

        c.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        c.setText("CONNECTER");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel2.add(c);
        c.setBounds(180, 210, 125, 30);

        q.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        q.setText("QUITTER");
        jPanel2.add(q);
        q.setBounds(340, 210, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication4/les images/professionnel-de-santé.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 300);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 710, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
         String req="select * from medecin where login='"+l.getText()+"' and password='"+p.getText()+"'";
                try{
            stm=(Statement) conn.obtenirconnexion().createStatement();
            ResultSet rs=stm.executeQuery(req);
            if (rs.next())
            {
                realiser1 R=new realiser1();
                R.setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null,"LOGIN ou MOT DE PASSE INCORRECT"); }
        }
        catch(SQLException ex){
            System.err.println(ex);
        }
    }//GEN-LAST:event_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medecinauth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medecinauth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medecinauth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medecinauth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medecinauth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField l;
    private javax.swing.JPasswordField p;
    private javax.swing.JButton q;
    // End of variables declaration//GEN-END:variables
}
